[package]
name = "ssvm_storage_interface"
version = "0.1.30"
authors = ["tpmccallum <mistermac2008@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/second-state/ssvm_storage_interface"
license-file = "LICENSE"
description = "A Rust library that provides Rust to WebAssembly developers with syntax for load and store functionality"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "^1.2"
serialize_deserialize_u8_i32 = "^0.1"
serde = { version = "1.0.105", features = ["derive"] }


